# Generated by Django 6.0.4 on 2026-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='quests/'),
        ),
    ]
