# Generated by Django 6.0.4 on 2026-05-10 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_quest_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('focus', 'Концентрація'), ('recovery', 'Відновлення'), ('xp_boost', 'Буст XP'), ('shield', 'Захист')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='priority',
            field=models.CharField(choices=[('low', 'Не треба'), ('medium', 'Бажано'), ('high', 'Треба'), ('critical', 'Або зараз, або ніколи')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rarity',
            field=models.CharField(choices=[('common', 'Звичайний'), ('rare', 'Нічогенький'), ('epic', 'Напряжний'), ('legendary', 'Дуже напряжний')], default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracker.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
