# Generated by Django 6.0.4 on 2026-05-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_item_description_item_last_used_alter_item_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['unlock_level', 'item_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='effect_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='stamina',
        ),
        migrations.AddField(
            model_name='item',
            name='unlock_level',
            field=models.PositiveIntegerField(choices=[(1, 'Lv.1'), (3, 'Lv.3'), (5, 'Lv.5'), (8, 'Lv.8'), (12, 'Lv.12')], default=1),
        ),
        migrations.AlterField(
            model_name='boss',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bosses', to='tracker.skill'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('focus', 'Концентрація'), ('recovery', 'Відновлення'), ('planning', 'Планування'), ('mindset', 'Мислення')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.item')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_items', to='tracker.quest')),
            ],
            options={
                'unique_together': {('quest', 'item')},
            },
        ),
    ]
